version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    assignees: ["metgen"]
    labels: ["dependencies"]

  # Docker base image
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "daily" }
    assignees: ["metgen"]
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore(deps): bump caddy"

  # Go modules (плагины)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule: { interval: "daily" }
    assignees: ["metgen"]
    labels: ["dependencies", "plugins"]
    commit-message:
      prefix: "chore(deps): bump plugins"